const { Router } = require("express");
const router = Router();
const category = require("./categories.routes.js");
const productMiddleware = require("./products.routes.js");
const countrys = require("./countrys.routes.js");
const drinks = require("./drinksIntegred.routes.js");
router.use("/categories", category);
router.use("/products", productMiddleware);
router.use("/countrys", countrys);
router.use("/drinks", drinks);
module.exports = router;
