require('dotenv').config();



const CLOUDINARY_NAME = process.env.CLOUDINARY_NAME || dcxiks4ku
const CLOUDINARY_KEY = process.env.CLOUDINARY_KEY || 384843649966795
const CLOUDINARY_SECRET = process.env.CLOUDINARY_SECRET || dLPUQ6zCKJQDBCstQ208JuS3Q40

module.exports = {CLOUDINARY_NAME,
CLOUDINARY_KEY,
CLOUDINARY_SECRET,
}